services:
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - USER_SERVICE_URL=http://user-microservice:3001
      - ATTENDANCE_SERVICE_URL=http://attendance-microservice:3002
    depends_on:
      - user-microservice
      - attendance-microservice

  user-microservice:
    build: ./user-microservice
    container_name: user-microservice
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGO_URI=mongodb+srv://gaaradanil:gaaradanil09@absence.qrs5aoa.mongodb.net/?retryWrites=true&w=majority&appName=absence
    command: ["node", "dist/main.js"]

  attendance-microservice:
    build: ./attendance-microservice
    container_name: attendance-microservice
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - MONGO_URI=mongodb+srv://gaaradanil:gaaradanil09@absence.qrs5aoa.mongodb.net/?retryWrites=true&w=majority&appName=absence
    command: ["node", "dist/main.js"]

  client-frontend:
    build: 
      context: ./client-fronted
      dockerfile: Dockerfile.prod
    container_name: client-frontend
    ports:
      - "8080:80"
    environment:
      - PORT=4000
      - VITE_API_URL=http://localhost:4000
      - USER_SERVICE_URL=http://localhost:3001
      - ATTENDANCE_SERVICE_URL=http://localhost:3002